name = "basic_topology"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["basic_topology"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = true
relaxedAutoImplicit = true
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
linter.style.commandStart = false
linter.style.longLine = false
linter.dupNamespace = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "basic_topology"
