name = "basic_topology"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["basic_topology"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = true
relaxedAutoImplicit = true
maxSynthPendingDepth = 3
weak.linter.mathlibStandardSet = true
weak.linter.style.longLine = false
weak.linter.style.commandStart = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "basic_topology"
